---
    - name: Create minio user
      ansible.builtin.user:
        name: 'minio'
        shell: /sbin/nologin

    - name: Check if minio service exists
      stat: path=/etc/systemd/system/minio.service
      register: minio_service_status

    - name: Stop service minio
      ansible.builtin.systemd:
        name: minio
        state: stopped
      when: minio_service_status.stat.exists

    - name: Download MinIO server executable
      ansible.builtin.get_url:
        url: https://dl.min.io/server/minio/release/linux-amd64/minio
        dest: /usr/local/bin/minio
        mode: 0755
        force: true

    - name: Create /etc/minio directory
      ansible.builtin.file:
        dest: /etc/minio
        state: directory
        owner: minio
        group: minio
        mode: 0755

    - name: Copy /etc/default/minio configuration
      ansible.builtin.template:
        src: minio.j2
        dest: /etc/default/minio
        owner: root
        group: root
        mode: 0640

    - name: Create /usr/local/share/minio directory
      ansible.builtin.file:
        dest: /usr/local/share/minio
        state: directory
        owner: minio
        group: minio
        mode: 0750

    - name: Copy minio.service configuration
      ansible.builtin.copy:
        src: minio.service
        dest: /etc/systemd/system/minio.service
        owner: root
        group: root
        mode: 0755

    - name: Force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable service minio
      ansible.builtin.systemd:
        name: minio
        enabled: yes

    - name: Start service minio
      ansible.builtin.systemd:
        name: minio
        state: started

    - name: Download MinIO client executable
      ansible.builtin.get_url:
        url: https://dl.min.io/client/mc/release/linux-amd64/mc
        dest: /usr/local/bin/mc
        mode: 0755
        force: true

    - name: Configure MinIO host for MinIO client
      ansible.builtin.shell: mc config host add minio {{ minio_api_scheme }}://{{ minio_api_address }}:{{ minio_api_port }}/ {{ minio_root_user }} {{ minio_root_password }}

    - name: Create MinIO user
      ansible.builtin.shell: mc admin user add minio {{ item['access_key'] }} {{ item['secret_key'] }}
      loop: '{{ minio_users }}'
